
name: Testing Go-Code

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - name: git clone
        uses: actions/checkout@v2
        
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check deps
        run: make go-deps

      - name: Check linter issues
        run: make lint

      - name: Run tests
        run: make test          

      - name: Upload cover files
        uses: actions/upload-artifact@v2
        with:
          name: cover_tests_report
          path: cover.*t*
          retention-days: 14

